# Dependencies
highlighter:      pygments

# Setup
title:            Wenjie Qu
tagline:          'Academic Webpage'
description:      'Undergraduate Researcher - Artificial Intelligence Security.'
url:              http://quwenjie.github.io
baseurl:          /
cover_image:  yeyuan.jpg

author:
name:           'Wenjie Qu'
email:          wenjiequ@hust.edu.cn

paginate:         6
paginate_path:    "/notes/page:num"

pages_list:
  - name: Publications
    loc: /publication.html
